### ISSUE TITLE
parse_dir function thoughts

### ISSUE THREAD

**Issue by Bas-Man** [bbustin/dmarc_aggregate_parser#9]
Hi @bbustin,
I have taken a longer look at `parse_dir()` and I think there are a few issues with the function. As you mentioned you put this together while learning Rust. I myself am still learning Rust :). I would personally use it for my own small projects. But it has some issues when being considered for use in the larger more complex system.

 - Unable to mark files as processed, or rename, remove files that have successfully been processed. This means that files need be manually updated to avoid duplication or reprocessing.
 - I also suspect that if there is a file that causes an error, any following files would not be processed until the offending file is fixed/removed.

The general approach I have used and seen used is something along the lines of the following *dodgy pseudo code*
```code 
for file in dir {
  file = parse()
  if file is ok {
    Do any work that needs to be done. 
    If there is a problem log and report issue and move to the next file without making any system changes.
    If the work completes successfully. Mark the file as processed or remove it.
  } else {
    log and report file as a problem
  }
}
```
This basically is the long way of saying the parse_dir function is great for testing :) but not so much for production environment as I see things.

**Comment by bbustin** [comment]
That is definitely one way it could be done.

This is just a simple library. That kind of functionality could be put in a project that uses this library. So maybe parse the directory in the other project, then use this library to parse individual files and mark them as parsed. It just seems like that kind of functionality might be out of scope for a simple library. It sounds more like business logic.

I was implementing something that leveraged this library and put the parsed results into a SQLite database for analysis. I never did finish. That mechanism to not reprocess files is something that I would put in there, if I ever finished it. I had a problem with nested fields and never had the time to get back to fixing it.
